name: Deploy to VPS

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/drafteam
          git pull origin production
          cd client && npm install && npm run build
          cd ../server && npm install
          pm2 restart drafteam-server
          echo "Deployment completed at $(date)"