name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/drafteam
          git fetch origin
          git reset --hard origin/main
          git pull origin main
          cd client
          npm ci
          npm run build
          ls -la build/
          npm cache clean --force
          cd ../server && npm install
          pip3 install -r ../requirements.txt
          pm2 restart drafteam-server
          echo "Deployment completed at $(date)"